trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: build
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  inputs:
    command: test
    publishTestResults: true
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  inputs: 
    command: pack
    configuration: $(buildConfiguration)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '**/$(buildConfiguration)/*.nupkg'