trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: GitVersion@5
  inputs:
    runtime: 'core'
    updateAssemblyInfo: true

- task: DotNetCoreCLI@2
  inputs:
    command: build
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  inputs:
    command: test
    publishTestResults: true
    configuration: $(buildConfiguration)

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/IdentifierSentence.nuspec'
    versioningScheme: 'byEnvVar'
    versionEnvVar: '$(GitVersion.FullSemVer)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'IdentifierSentence.$(GitVersion.FullSemVer).nupkg'